<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>V:\SRMVR\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="AssetRipper.CIL">
      <HintPath>V:\SRMVR\BepInEx\core\AssetRipper.CIL.dll</HintPath>
    </Reference>
    <Reference Include="AssetRipper.Primitives">
      <HintPath>V:\SRMVR\BepInEx\core\AssetRipper.Primitives.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Core">
      <HintPath>V:\SRMVR\BepInEx\core\BepInEx.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Preloader.Core">
      <HintPath>V:\SRMVR\BepInEx\core\BepInEx.Preloader.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity.Common">
      <HintPath>V:\SRMVR\BepInEx\core\BepInEx.Unity.Common.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>V:\SRMVR\BepInEx\core\BepInEx.Unity.IL2CPP.dll</HintPath>
    </Reference>
    <Reference Include="Common">
      <HintPath>V:\SRMVR\BepInEx\interop\Common.dll</HintPath>
    </Reference>
    <Reference Include="Constants">
      <HintPath>V:\SRMVR\BepInEx\interop\Constants.dll</HintPath>
    </Reference>
    <Reference Include="Cpp2IL.Core">
      <HintPath>V:\SRMVR\BepInEx\core\Cpp2IL.Core.dll</HintPath>
    </Reference>
    <Reference Include="Gee.External.Capstone">
      <HintPath>V:\SRMVR\BepInEx\core\Gee.External.Capstone.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>V:\SRMVR\BepInEx\core\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>V:\SRMVR\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppSystemDataApplierService">
      <HintPath>V:\SRMVR\BepInEx\interop\Il2CppSystemDataApplierService.dll</HintPath>
    </Reference>
    <Reference Include="LibCpp2IL">
      <HintPath>V:\SRMVR\BepInEx\core\LibCpp2IL.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.Backports">
      <HintPath>V:\SRMVR\BepInEx\core\MonoMod.Backports.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>V:\SRMVR\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
